name: PR checks
on: pull_request

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: DOCKER_BUILDKIT=1 docker build --tag microstack-run .

    - name: Run image
      run: |
        docker run -d -p 80:80 microstack-run
        sleep 1
        curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost

  run-dotrun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dotrun
        run: |
          sudo snap install dotrun
          sudo chown root:root /
      - name: Install dependencies
        run: /snap/bin/dotrun install

      - name: Build assets
        run: /snap/bin/dotrun build

      - name: Run dotrun
        run: |
          /snap/bin/dotrun &
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:8039

  lint-nginx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install gixy
        run: pip3 install gixy

      - name: Lint nginx configuration files
        run: yarn lint-nginx

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss
