name: PR checks
on: pull_request

env:
  SECRET_KEY: local_development_fake_key

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag microstack-run .
      - name: Run image
        run: |
          docker run -d -p 80:80 --env SECRET_KEY=insecure_secret_key microstack-run
          sleep 1 && curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost

  run-dotrun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dotrun
        run: |
          sudo snap install dotrun
          sudo chown root:root /

      - name: Install dependencies
        run: /snap/bin/dotrun install

      - name: Build assets
        run: /snap/bin/dotrun build

      - name: Test site
        run: |
          /snap/bin/dotrun &
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:8039

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Install python dependencies
        run: |
          sudo pip3 install --upgrade pip
          sudo pip3 install flake8 black

      - name: Lint python
        run: yarn lint-python

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss

  test-python:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install requirements
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Install dependencies
        run: sudo pip3 install coverage

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Build resources
        run: yarn build

      - name: Run tests with coverage
        run: |
          coverage run  --source=. -m unittest discover tests
          bash <(curl -s https://codecov.io/bash) -cF python

  test-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test JS
        run: |
          yarn test-js
          bash <(curl -s https://codecov.io/bash) -cF javascript

  check-inclusive-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail-on-error: true
